name: "HCL AppScan SAST"
on:
  workflow_dispatch

env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run AppScan SAST scan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.2
        with:
          asoc_key: ${{ secrets.ASOC_KEY2 }}
          asoc_secret: ${{ secrets.ASOC_SECRET2 }}
          application_id: 30a2d6ab-e765-4931-b3fa-15825295e261
          wait_for_analysis: true
          fail_for_noncompliance: true
