# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "HCL AppScan Code Scan"

on:
  pull_request:
    types: [opened,synchronize]
  push:
    branches:
    - main
    - develop
  workflow_dispatch: 

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ASOC_KEY: ${{ secrets.ASOC_KEY}}
  ASOC_SECRET: ${{ secrets.ASOC_SECRET }}

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run AppScan Code Scan
        uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
        with:
          asoc_key: ${{ env.ASOC_KEY}}
          asoc_secret: ${{ env.ASOC_SECRET }}
          publish_on_merge: true
          application_id: 30a2d6ab-e765-4931-b3fa-15825295e261
          issue_status: "inprogress"
          scan_base_name: "CodeSweep"
          personal_scan: true
